apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: staticgatewayconfigurations.egressgateway.kubernetes.azure.com
spec:
  group: egressgateway.kubernetes.azure.com
  names:
    kind: StaticGatewayConfiguration
    listKind: StaticGatewayConfigurationList
    plural: staticgatewayconfigurations
    singular: staticgatewayconfiguration
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: StaticGatewayConfiguration is the Schema for the staticgatewayconfigurations
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: StaticGatewayConfigurationSpec defines the desired state
              of StaticGatewayConfiguration
            properties:
              defaultRoute:
                default: staticEgressGateway
                description: Pod default route, should be either azureNetworking (pod's
                  eth0) or staticEgressGateway (default).
                enum:
                - azureNetworking
                - staticEgressGateway
                type: string
              excludeCidrs:
                description: CIDRs to be excluded from the default route.
                items:
                  type: string
                type: array
              gatewayNodepoolName:
                description: Name of the gateway nodepool to apply the gateway configuration.
                type: string
              gatewayVmssProfile:
                description: Profile of the gateway VMSS to apply the gateway configuration.
                properties:
                  publicIpPrefixSize:
                    description: Public IP prefix size to be applied to this VMSS.
                    format: int32
                    maximum: 31
                    minimum: 0
                    type: integer
                  vmssName:
                    description: Name of the VMSS
                    type: string
                  vmssResourceGroup:
                    description: Resource group of the VMSS. Must be in the same subscription.
                    type: string
                type: object
              provisionPublicIps:
                default: true
                description: Whether to provision public IP prefixes for outbound.
                type: boolean
              publicIpPrefixId:
                description: BYO Resource ID of public IP prefix to be used as outbound.
                  This can only be specified when provisionPublicIps is true.
                type: string
            required:
            - provisionPublicIps
            type: object
          status:
            description: StaticGatewayConfigurationStatus defines the observed state
              of StaticGatewayConfiguration
            properties:
              egressIpPrefix:
                description: Egress IP Prefix CIDR used for this gateway configuration.
                type: string
              gatewayServerProfile:
                description: Gateway server profile.
                properties:
                  ip:
                    description: Gateway IP for connection.
                    type: string
                  port:
                    description: Listening port of the gateway server.
                    format: int32
                    type: integer
                  privateKeySecretRef:
                    description: Reference of the secret that holds gateway side private
                      key.
                    properties:
                      apiVersion:
                        description: API version of the referent.
                        type: string
                      fieldPath:
                        description: 'If referring to a piece of an object instead
                          of an entire object, this string should contain a valid
                          JSON/Go field access statement, such as desiredState.manifest.containers[2].
                          For example, if the object reference is to a container within
                          a pod, this would take on a value like: "spec.containers{name}"
                          (where "name" refers to the name of the container that triggered
                          the event) or if no container name is specified "spec.containers[2]"
                          (container with index 2 in this pod). This syntax is chosen
                          only to have some well-defined way of referencing a part
                          of an object. TODO: this design is not final and this field
                          is subject to change in the future.'
                        type: string
                      kind:
                        description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                        type: string
                      name:
                        description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                        type: string
                      namespace:
                        description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                        type: string
                      resourceVersion:
                        description: 'Specific resourceVersion to which this reference
                          is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency'
                        type: string
                      uid:
                        description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                        type: string
                    type: object
                    x-kubernetes-map-type: atomic
                  publicKey:
                    description: Gateway server public key.
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: gatewaylbconfigurations.egressgateway.kubernetes.azure.com
spec:
  group: egressgateway.kubernetes.azure.com
  names:
    kind: GatewayLBConfiguration
    listKind: GatewayLBConfigurationList
    plural: gatewaylbconfigurations
    singular: gatewaylbconfiguration
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: GatewayLBConfiguration is the Schema for the gatewaylbconfigurations
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: GatewayLBConfigurationSpec defines the desired state of GatewayLBConfiguration
            properties:
              gatewayNodepoolName:
                description: Name of the gateway nodepool to apply the gateway configuration.
                type: string
              gatewayVmssProfile:
                description: Profile of the gateway VMSS to apply the gateway configuration.
                properties:
                  publicIpPrefixSize:
                    description: Public IP prefix size to be applied to this VMSS.
                    format: int32
                    maximum: 31
                    minimum: 0
                    type: integer
                  vmssName:
                    description: Name of the VMSS
                    type: string
                  vmssResourceGroup:
                    description: Resource group of the VMSS. Must be in the same subscription.
                    type: string
                type: object
              provisionPublicIps:
                default: true
                description: Whether to provision public IP prefixes for outbound.
                type: boolean
              publicIpPrefixId:
                description: BYO Resource ID of public IP prefix to be used as outbound.
                type: string
            required:
            - provisionPublicIps
            type: object
          status:
            description: GatewayLBConfigurationStatus defines the observed state of
              GatewayLBConfiguration
            properties:
              egressIpPrefix:
                description: Egress IP Prefix CIDR used for this gateway configuration.
                type: string
              frontendIp:
                description: Gateway frontend IP.
                type: string
              serverPort:
                description: Listening port of the gateway server.
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gatewayvmconfigurations.egressgateway.kubernetes.azure.com
spec:
  group: egressgateway.kubernetes.azure.com
  names:
    kind: GatewayVMConfiguration
    listKind: GatewayVMConfigurationList
    plural: gatewayvmconfigurations
    singular: gatewayvmconfiguration
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: GatewayVMConfiguration is the Schema for the gatewayvmconfigurations API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: GatewayVMConfigurationSpec defines the desired state of GatewayVMConfiguration
            properties:
              gatewayNodepoolName:
                description: Name of the gateway nodepool to apply the gateway configuration.
                type: string
              gatewayVmssProfile:
                description: Profile of the gateway VMSS to apply the gateway configuration.
                properties:
                  publicIpPrefixSize:
                    description: Public IP prefix size to be applied to this VMSS.
                    format: int32
                    maximum: 31
                    minimum: 0
                    type: integer
                  vmssName:
                    description: Name of the VMSS
                    type: string
                  vmssResourceGroup:
                    description: Resource group of the VMSS. Must be in the same subscription.
                    type: string
                type: object
              provisionPublicIps:
                default: true
                description: Whether to provision public IP prefixes for outbound.
                type: boolean
              publicIpPrefixId:
                description: BYO Resource ID of public IP prefix to be used as outbound.
                type: string
            required:
            - provisionPublicIps
            type: object
          status:
            description: GatewayVMConfigurationStatus defines the observed state of GatewayVMConfiguration
            properties:
              egressIpPrefix:
                description: The egress source IP for traffic using this configuration.
                type: string
              gatewayVMProfiles:
                description: Gateway VM profile
                items:
                  description: GatewayVMProfile provides details about gateway VM
                    side configuration.
                  properties:
                    nodeName:
                      type: string
                    primaryIP:
                      type: string
                    secondaryIP:
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: gatewaystatuses.egressgateway.kubernetes.azure.com
spec:
  group: egressgateway.kubernetes.azure.com
  names:
    kind: GatewayStatus
    listKind: GatewayStatusList
    plural: gatewaystatuses
    singular: gatewaystatus
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: GatewayStatus is the Schema for the gatewaystatuses API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: GatewayStatusSpec defines the desired state of GatewayStatus
            properties:
              readyGatewayConfigurations:
                description: List of ready gateway configurations
                items:
                  properties:
                    interfaceName:
                      description: Network interface name
                      type: string
                    staticGatewayConfiguration:
                      description: StaticGatewayConfiguration in <namespace>/<name>
                        pattern
                      type: string
                  type: object
                type: array
              readyPeerConfigurations:
                description: List of ready peer configurations
                items:
                  properties:
                    interfaceName:
                      description: Network interface name
                      type: string
                    podEndpoint:
                      description: PodEndpoint in <namespace>/<name> pattern
                      type: string
                    publicKey:
                      description: Public Key
                      type: string
                  type: object
                type: array
            type: object
          status:
            description: GatewayStatusStatus defines the observed state of GatewayStatus
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: podendpoints.egressgateway.kubernetes.azure.com
spec:
  group: egressgateway.kubernetes.azure.com
  names:
    kind: PodEndpoint
    listKind: PodEndpointList
    plural: podendpoints
    singular: podendpoint
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: PodEndpoint is the Schema for the podendpoints API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PodEndpointSpec defines the desired state of PodEndpoint
            properties:
              podIpAddress:
                description: IPv4 address assigned to the pod.
                type: string
              podPublicKey:
                description: public key on pod side.
                type: string
              staticGatewayConfiguration:
                description: Name of StaticGatewayConfiguration the pod uses.
                type: string
            type: object
          status:
            description: PodEndpointStatus defines the observed state of PodEndpoint
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
